export enum Cyrillic {
    // --- Cyrillic letters ---
    /** Cyrillic small letter a (а) */ A="а",
    /** Cyrillic small letter be (б) */ BE="б",
    /** Cyrillic small letter ve (в) */ VE="в",
    /** Cyrillic small letter ghe (г) */ GHE="г",
    /** Cyrillic small letter de (д) */ DE="д",
    /** Cyrillic small letter ye (е) */ YE="е",
    /** Cyrillic small letter yo (ё) */ YO="ё",
    /** Cyrillic small letter zhe (ж) */ ZHE="ж",
    /** Cyrillic small letter ze (з) */ ZE="з",
    /** Cyrillic small letter i (и) */ I="и",
    /** Cyrillic small letter short i (й) */ SHORT_I="й",
    /** Cyrillic small letter ka (к) */ KA="к",
    /** Cyrillic small letter el (л) */ EL="л",
    /** Cyrillic small letter em (м) */ EM="м",
    /** Cyrillic small letter en (н) */ EN="н",
    /** Cyrillic small letter o (о) */ O="о",
    /** Cyrillic small letter pe (п) */ PE="п",
    /** Cyrillic small letter er (р) */ ER="р",
    /** Cyrillic small letter es (с) */ ES="с",
    /** Cyrillic small letter te (т) */ TE="т",
    /** Cyrillic small letter u (у) */ U="у",
    /** Cyrillic small letter ef (ф) */ EF="ф",
    /** Cyrillic small letter ha (х) */ HA="х",
    /** Cyrillic small letter tse (ц) */ TSE="ц",
    /** Cyrillic small letter che (ч) */ CHE="ч",
    /** Cyrillic small letter sha (ш) */ SHA="ш",
    /** Cyrillic small letter shcha (щ) */ SHCHA="щ",
    /** Cyrillic small letter hard sign (ъ) */ HARD_SIGN="ъ",
    /** Cyrillic small letter yeru (ы) */ YERU="ы",
    /** Cyrillic small letter soft sign (ь) */ SOFT_SIGN="ь",
    /** Cyrillic small letter e (э) */ E="э",
    /** Cyrillic small letter yu (ю) */ YU="ю",
    /** Cyrillic small letter ya (я) */ YA="я"
}